// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsVzv41nlrt_4eCHAbdJfI7YmSRw5zQJI',
    appId: '1:317636765228:web:23634900a51addda84d389',
    messagingSenderId: '317636765228',
    projectId: 'video-feed-app',
    authDomain: 'video-feed-app.firebaseapp.com',
    storageBucket: 'video-feed-app.firebasestorage.app',
    measurementId: 'G-GTNSDFMWVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRUHhCK-eJFfb0Swr-8QEhl07_sdaDxK8',
    appId: '1:317636765228:android:8a2cf3826bfbc70b84d389',
    messagingSenderId: '317636765228',
    projectId: 'video-feed-app',
    storageBucket: 'video-feed-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb4YEgimB8_n6Qgugee7p6rRKUI2aUQl8',
    appId: '1:317636765228:ios:75ecf3dc5ed26df984d389',
    messagingSenderId: '317636765228',
    projectId: 'video-feed-app',
    storageBucket: 'video-feed-app.firebasestorage.app',
    iosClientId: '317636765228-jqp7pf21sl74tpp5ie70tt33efq8p327.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb4YEgimB8_n6Qgugee7p6rRKUI2aUQl8',
    appId: '1:317636765228:ios:75ecf3dc5ed26df984d389',
    messagingSenderId: '317636765228',
    projectId: 'video-feed-app',
    storageBucket: 'video-feed-app.firebasestorage.app',
    iosClientId: '317636765228-jqp7pf21sl74tpp5ie70tt33efq8p327.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsVzv41nlrt_4eCHAbdJfI7YmSRw5zQJI',
    appId: '1:317636765228:web:0cf2444f8b1306ad84d389',
    messagingSenderId: '317636765228',
    projectId: 'video-feed-app',
    authDomain: 'video-feed-app.firebaseapp.com',
    storageBucket: 'video-feed-app.firebasestorage.app',
    measurementId: 'G-FHTQ6J0PV9',
  );
}
